// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq5shIfjLYionvQegRyC4YCoLYIxP6EGA',
    appId: '1:667750783737:web:6973d3e7e5f3ddd9c56028',
    messagingSenderId: '667750783737',
    projectId: 'monkey-hill-climb',
    authDomain: 'monkey-hill-climb.firebaseapp.com',
    databaseURL: 'https://monkey-hill-climb-default-rtdb.firebaseio.com',
    storageBucket: 'monkey-hill-climb.appspot.com',
    measurementId: 'G-8M9GPBYMPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCekY4dMp_S45Ur-iF3gLkeODvzuh8No50',
    appId: '1:667750783737:android:b4c18003da77b1aec56028',
    messagingSenderId: '667750783737',
    projectId: 'monkey-hill-climb',
    databaseURL: 'https://monkey-hill-climb-default-rtdb.firebaseio.com',
    storageBucket: 'monkey-hill-climb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy5eIb1aBLomKBr4sk36pyHVFGNpiMIE0',
    appId: '1:667750783737:ios:a3d6f7d568474836c56028',
    messagingSenderId: '667750783737',
    projectId: 'monkey-hill-climb',
    databaseURL: 'https://monkey-hill-climb-default-rtdb.firebaseio.com',
    storageBucket: 'monkey-hill-climb.appspot.com',
    androidClientId: '667750783737-599tbmaipane2d9tk3q4c2m4iqgo7ruv.apps.googleusercontent.com',
    iosClientId: '667750783737-h9tkotjpvbkrd5jsgm068gjttvhs8p9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ftAlpineWeb',
  );
}
